version: "3.7"
services:
    web:
        image: "php:7.4-apache"
        container_name: php-container
        restart: always
        volumes:
            - ./app:/var/www/html
        ports:
            - "8000:80"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 5s
            timeout: 1s
            retries: 2
            start_period: 0s
